version: 1.0.{build}
os: Visual Studio 2015
platform: Any CPU

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd InstagramApi
  - ps: dotnet --verbose build
  
test: off 
