version: 1.0.{build}
os: Visual Studio 2015
platform: Any CPU
branches:
  only:
    - release

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore
  - ps: cd InstagramApi
  - ps: dotnet --verbose build
  - ps: cd ../InstagramApi.Tests
  - ps: dotnet restore
  - ps: dotnet --verbose build
  - ps: dotnet --verbose test

test: off
